---
sudo: required

env:
  - distribution: ubuntu
    version: xenial

services:
  - docker


before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=.ci/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible .ci'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/vaizard.mage-base-common:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-galaxy install -r  /etc/ansible/roles/vaizard.mage-base-common/.ci/requirements.yml'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/vaizard.mage-base-common/.ci/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/vaizard.mage-base-common/.ci/test.yml --skip-tags entropy'
  - 'sudo docker rm -f "$(cat ${container_id})"'
