---

- name: "Including distro-specific variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"

- name: "Setting things up for {{ ansible_distribution }}"
  include: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu', 'Gentoo', 'Debian', 'Fedora' ]
  tags: [ 'install' ]

- name: "Making sure a default self-signed cert is present"
  command: openssl req -newkey rsa:4096 -x509 -nodes -days 3650 -sha512 -subj "/C=US/L=LA/O=VAIZ/OU=IT/CN={{ ansible_fqdn }}" -keyout /etc/ssl/private/mage-snakeoil.key -out /etc/ssl/certs/mage-snakeoil.pem
  args:
    creates: "/etc/ssl/private/mage-snakeoil.key"
  tags: [ 'configure' ]

- name: "Making sure a combine self-signed cert is present too"
  command: openssl req -newkey rsa:4096 -x509 -nodes -days 3650 -sha512 -subj "/C=US/L=LA/O=VAIZ/OU=IT/CN={{ ansible_fqdn }}" -keyout /etc/ssl/private/mage-snakeoil-combined.pem -out /etc/ssl/private/mage-snakeoil-combined.pem
  args:
    creates: "/etc/ssl/private/mage-snakeoil-combined.pem"
  tags: [ 'configure' ]

- name: "Ensure snakeoil keys are accessible only by root"
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - /etc/ssl/private/mage-snakeoil.key
    - /etc/ssl/private/mage-snakeoil-combined.pem

- name: "Ensure snakeoil cert has propper permissions"
  file:
    path: /etc/ssl/certs/mage-snakeoil.pem
    owner: root
    group: root
    mode: 0644

- name: "Making sure dhparam file is present"
  command: openssl dhparam -out /etc/ssl/private/dhparams.pem "{{ dhparam_size }}" creates=/etc/ssl/private/dhparams.pem
  tags: [ 'configure' ]

  # Rhel based distros don't have a locale-gen command, Debian and Ubuntu will use mage-locales
- name: "Ensure locale en_US.UTF-8 locale is present"
  locale_gen:
    name: en_US.UTF-8
    state: present
  when: ansible_distribution not in [ 'Redhat', 'Centos', 'Fedora', 'Debian', 'Ubuntu' ]
  tags: [ 'configure' ]


- name: "Ensure locale en_US.UTF locale is present"
  include_role:
    name: mage-locales
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
  tags: [ 'configure' ]

