---

- name: "Add Universe repo"
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"

- name: "Installing packages"
  apt:
    name: "{{ mage_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
