---

# As long as Canonical happily keeps a bugged package unpatched
# and as long as Redhat insists on releasing Ansible with nasty
# bugs, this stays here, even for systems that will never get
# Ansible installed on. Because you never know and you don't want
# to spend hours tracing disasterous bugs all over the place.
- name: "Add Ansible PPA"
  apt_repository:
    repo: ppa:ansible/ansible

- name: "Installing packages"
  apt:
    name: "{{ mage_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
